name: Pull request CI checks

on: [pull_request]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Style check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: burrunan/gradle-cache-action@v1
        name: Spotless check
        with:
          gradle-dependencies-cache-key: |
            buildSrc/**/Dependencies.kt
            **/gradle-wrapper.properties
          arguments: |
            spotlessCheck

  debug_build:
    name: Debug build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: burrunan/gradle-cache-action@v1
        name: Build debug
        with:
          gradle-dependencies-cache-key: |
            buildSrc/**/Dependencies.kt
            **/gradle-wrapper.properties
          arguments: |
            assembleApiQDebug

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - uses: burrunan/gradle-cache-action@v1
        name: Build debug
        with:
          gradle-dependencies-cache-key: |
            buildSrc/**/Dependencies.kt
            **/gradle-wrapper.properties
          arguments: |
            testDebugUnitTest

      - name: Upload testDebugUnitTest results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: testDebugUnitTest
          path: ./**/build/reports/tests/testDebugUnitTest
