name: Pre release (beta)

on:
  release:
    types: [prereleased]

jobs:
  published:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Publish apk to beta track
        run: echo "Publishing apk to beta track"