name: Release apk

on:
  release:
    types: [released]

jobs:
  published:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Publish release apk to PlayStore
        run: echo "Publishing apk to playstore"